name: FoundDiamonds
version: 3.6.4
main: co.proxa.founddiamonds.FoundDiamonds
author: proxa
website: http://dev.bukkit.org/server-mods/founddiamonds/
description: Block announcer and anti x-ray
dev-url: http://dev.bukkit.org/server-mods/founddiamonds/

commands:
   fd:
     description: Shows the main menu
     aliases: [founddiamonds]
     permission-message: Sorry, you do not have permission

permissions:
  fd.*:
    description: Gives access to all FD commands
    default: false
    children:
      fd.trap: true
      fd.admin: true
      fd.manage.*: true
      fd.broadcast: true
      fd.monitor: true
      fd.admin: true

  fd.manage.*:
    description: Allows management of all blocks
    default: false
    children:
      fd.manage.admin.add: true
      fd.manage.admin.remove: true
      fd.manage.admin.list: true
      fd.manage.broadcast.add: true
      fd.manage.broadcast.remove: true
      fd.manage.broadcast.list: true
      fd.manage.light.add: true
      fd.manage.light.remove: true
      fd.manage.light.list: true
      fd.manage.toggle: true
      fd.manage.config: true
      fd.manage.world: true
      fd.manage.reload: true

  fd.manage.admin.*:
    description: Allows management of all admin message blocks
    default: false
    children:
      fd.manage.admin.add: true
      fd.manage.admin.remove: true
      fd.manage.admin.list: true

  fd.manage.light.*:
    description: Allows management of all light level blocks
    default: false
    children:
      fd.manage.light.add: true
      fd.manage.light.remove: true
      fd.manage.light.list: true

  fd.manage.broadcast.*:
    description: Allows management of all broadcast blocks
    default: false
    children:
      fd.manage.broadcast.add: true
      fd.manage.broadcast.remove: true
      fd.manage.broadcast.list: true

  fd.trap.*:
    description: Allows management of all trap blocks
    default: false
    children:
      fd.trap.remove.self: true
      fd.trap.remove.all: true
      fd.trap.set: true
      fd.trap.list: true

  fd.trap.remove.*:
    description: Allows removal of all trap blocks
    default: false
    children:
      fd.trap.remove.self: true
      fd.trap.remove.all: true

  fd.manage.reload:
    description: Allows users to reload the configuration file in game
    default: false

  fd.manage.config:
    description: Allows users to view the FD configuration file in game
    default: false

  fd.manage.toggle:
    description: Allows users to change the configuration file in game
    default: false

  fd.manage.world:
    description: Allows edit FD enabled worlds in game
    default: false

  fd.manage.broadcast.add:
    description: Allows adding of broadcasted blocks
    default: false
  fd.manage.broadcast.remove:
    description: Allows removal of broadcasted blocks
    default: false
  fd.manage.broadcast.list:
    description: Allows listing of all broadcasted blocks
    default: false

  fd.manage.admin.add:
    description: Allows adding of admin message blocks
    default: false
  fd.manage.admin.remove:
    description: Allows removal of admin message blocks
    default: false
  fd.manage.admin.list:
    description: Allows listing of admin message blocks
    default: false

  fd.manage.light.add:
    description: Allows adding of light level blocks
    default: false
  fd.manage.light.remove:
    description: Allows removal of light level blocks
    default: false
  fd.manage.light.list:
    description: Allows listing of light level blocks
    default: false

  fd.trap.remove.self:
    description: Allows removal of a players own trap blocks
    default: false
  fd.trap.remove.all:
    description: Allows removal of any and all trap blocks
    default: false
  fd.trap.set:
    description: Allows a player to set traps
    default: false
  fd.trap.list:
    description: Allows a player to list trap blocks
    default: false

  fd.broadcast:
    description: Broadcasts to player
    default: false

  fd.monitor:
    description: Monitors the players light level
    default: false
